x-common-env: &common-env
  SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/studify
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
  AWS_ENDPOINT: http://localstack:4566
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  AWS_REGION: us-east-1

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: studify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:4.4.0
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      LOCALSTACK_PERSISTENCE: 1
    volumes:
      - localstack-data:/var/lib/localstack
      - ./scripts:/etc/localstack/init/ready.d
    healthcheck:
      test: ["CMD-SHELL", "awslocal s3 ls"]
      interval: 5s
      timeout: 10s
      retries: 15

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      <<: *common-env
    depends_on:
      db:
        condition: service_healthy
      localstack:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8080/auth
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata:
  localstack-data:
